# -*- coding: utf-8 -*-
"""23

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FPC3jci_0r8iRLx5l94vpIXCcEhkmw8
"""

def input_user():
  '''meminta input user'''
  hargaBarang =float(input("masukkan harga barang: "))
  nilaiDiskon =float(input("masukkan harga barang (%):"))
  return hargaBarang,nilaiDiskon

def total_setelah_diskon(hargaBarang, nilaiDiskon):
    '''menghitung total setelah diskon'''
    return hargaBarang - (hargaBarang * (nilaiDiskon/100))

while True:

      harga,diskon = input_user()
      result = total_setelah_diskon(harga,diskon)

      isContinue = input("apakah lanjut")
      if isContinue == "n":
        break



hewan = ["singa","kambing","sapi"]
buah = ["apel","kiwi","magga"]
hewan.extend(buah)
print(hewan)

hewan = ["singa","kambing","sapi"]
print("kambing" in hewan)

hewans = ["singa","kambing","sapi"]
for hewan in hewans :
  print(hewan)



angka_2 = "88"
print(float(angka_2))

angka_2 = "44"
print(int(angka_2))

while True :
  try:
    usia=float(input("masukkan usia anda: "))
    print(f"usia anda adalah {usia}")

  except ValueError :
    print("harap masukkan angka yang valid")
print(f"usia anda adalah {usia}")





mobil = ["bmw","honda"]
mobil.append("nissan")

mobil.insert(1, "toyota")

motor = ["yamaha,suzuki"]
 mobil.extend(motor)
 print(mobil)





def input_user():
  '''meminta input user'''
  celcius =float(input("masukkan angka: "))
  return celcius

def conversi(celcius):
  fahrenheit = (9/5 * celcius) + 32
  return fahrenheit

while True:
  CELCIUS=input_user()
  result = conversi(CELCIUS)

  print(f"suhu dalam fahrenheit: {result}")

  isContinue = input("apakah lanjut")
  if isContinue == "n":
    break